# Generated by Django 4.2.21 on 2025-06-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
