# Generated by Django 4.2.21 on 2025-06-12 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_unit_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
