# Generated by Django 4.2.21 on 2025-06-16 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
