# Generated by Django 5.2.3 on 2025-08-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_teacher_first_name_alter_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
