# Generated by Terraform — do not edit manually
# Environment: ${environment}

services:
  db:
    image: postgres:15-alpine
    container_name: ${app_name}_${environment}_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${app_name}_${environment}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ../../../
    container_name: ${app_name}_${environment}_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "${debug}"
      SECRET_KEY: ${secret_key}
      DATABASE_URL: ${database_url}
      ALLOWED_HOSTS: ${allowed_hosts}
      CSRF_TRUSTED_ORIGINS: ${csrf_trusted_origins}
      LOG_LEVEL: ${log_level}
    ports:
      - "${port}:${port}"
    volumes:
      - media_data:/app/media

volumes:
  postgres_data:
  media_data:
