# Generated by Terraform — do not edit manually
# Environment: ${environment}

DEBUG=${debug}
SECRET_KEY=${secret_key}
DATABASE_URL=${database_url}
ALLOWED_HOSTS=${allowed_hosts}
CSRF_TRUSTED_ORIGINS=${csrf_trusted_origins}
LOG_LEVEL=${log_level}
